apiVersion: 1
datasources:
  - name: btlogger
    uid: btlogger-tsdb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: btlogger
    isDefault: true
    jsonData:
      database: btlogger
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: btlogger
